### ISSUE TITLE
Where is ./train/husky_paint-husky_real-style_map_3_full.npy

### ISSUE THREAD

**Issue by HenryCaiHaiying** [machrisaa/stylenet#2]
patches map finished 0 3.54528403282
finished joining patches 5.4882171154
Traceback (most recent call last):
  File "stylenet_patch.py", line 342, in <module>
    "./images/husky_paint_region.jpg", "./test_data/husky_real_region.jpg", height=500)
  File "stylenet_patch.py", line 330, in render_gen
    output_file=output_file)
  File "stylenet_patch.py", line 141, in render
    blur_mapping=blur_mapping)
  File "/Users/hcai/work/ai/stylenet/stylenet_core.py", line 240, in get_style_cost_patch2
    np.save(full_patch_file, full_patch_out)
  File "/Library/Python/2.7/site-packages/numpy/lib/npyio.py", line 477, in save
    fid = open(file, "wb")
IOError: [Errno 2] No such file or directory: './train/husky_paint-husky_real-style_map_3_full.npy'

**Comment by machrisaa** [comment]
this is the name of the file to be saved. may you try to create a folder called "train" in the project directory and try to run again?

**Comment by HenryCaiHaiying** [comment]
Yes, creating the 'train' folder worked.

After running for an hour, it crashed on generation 2, step 10.

I saw some meta files are over 2GB: 
   2110825568 Oct 17 16:54 saves-output-g0-80-80.meta

Step 10: cost:0.0055563813  (173.3 sec)      content:0.00000, style_3:0.00162, style_4:0.00394, gram:0.00000, diff_cost_out:0.00000
Traceback (most recent call last):
  File "stylenet_patch.py", line 342, in <module>
    "./images/husky_paint_region.jpg", "./test_data/husky_real_region.jpg", height=500)
  File "stylenet_patch.py", line 330, in render_gen
    output_file=output_file)
  File "stylenet_patch.py", line 237, in render
    global_step=global_step)
  File "/Users/hcai/work/ai/tf/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1287, in save
    self.export_meta_graph(meta_graph_filename)
  File "/Users/hcai/work/ai/tf/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1310, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/Users/hcai/work/ai/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2250, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/Users/hcai/work/ai/tf/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2213, in _as_graph_def
    raise ValueError("GraphDef cannot be larger than 2GB.")
ValueError: GraphDef cannot be larger than 2GB.

**Comment by machrisaa** [comment]
> After running for an hour, it crashed on generation 2, step 10.
> I am not very sure about your problem. It would not take an hour to build the graph and run for 10 steps only. Usually it only takes at most 1 min to finish the graph creation.

May you send me the detail about your running machine please? Like the GPU model, CPU model, OS, RAM, etc.
Also, please send me which version of Tensorflow and Python are you using.

As for the meta file, you can try to disable the creation of the .meta file by adding `write_meta_graph=False`.Like this:
`
                saved_path = saver.save(sess, "./train/saves-" + get_filename(content_file),
                                        global_step=global_step, write_meta_graph=False)
`

**Comment by HenryCaiHaiying** [comment]
After that line change to disable .meta file creation, the program successfully finishes.

Thanks.
